# Generated by Django 3.2.4 on 2021-07-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorya', '0002_soru_soru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soru',
            name='user',
        ),
    ]
