# Generated by Django 3.2.4 on 2021-07-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorya', '0004_auto_20210702_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='soru',
            name='aciklama',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
