# Generated by Django 3.2.4 on 2021-07-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorya', '0005_soru_aciklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soru',
            name='aciklama',
        ),
    ]
